#!/bin/bash
###########################################
#                                         #
#         ______)                         #
#        (, /         /)                  #
#          /  _  _   (/_ _   _            #
#       ) / _(/_(_(_/_) (_(_(_/_          #
#      (_/                 .-/            #
#                         (_/             #
#                                         #
#                    CoGe's Utility Belt  #
#                                         #
###########################################


#################################
#       Bash Color Codes        #
#################################

red=$(tput setaf 1)
green=$(tput setaf 2)
strong=$(tput bold)
normal=$(tput sgr0)
underline=$(tput smul)

##################################
#    Configuration Settings      #
##################################

CONF_DIR='/opt/apache2/coge/coge.conf'
PROJECT_DIR='/opt/apache2/Greentea/'
LOG_FILE='/opt/apache2/Greentea/logs/error.log'
URL='geco.iplantc.org/analytics'
FONT='invita'
LOGO="${green}\n`echo "Greentea" | figlet -f $FONT`${normal}"

##################################
#      Function Definitions      #
##################################

function GreenteaRunner {

    if [ ! "$(pgrep -f 'lein/')" ]
    then
        # Change into leiningen directory
        printf "|-\-\-\-\-> Changing Into %s %-8s" "$PROJECT_DIR"
        cd "$PROJECT_DIR"
        printf "[ ${green}OK${normal} ]\n"

        printf "|-\-\-\-\-> Restarting Greentea %-25s"
        lein run &> "$LOG_FILE" &
        printf "[ ${green}OK${normal} ]\n"

        # Change back into previous directory
        cd - &> /dev/null

        printf "|-\-\-\-\-> Restarting Apache %-27s"
        service apache2 restart &> /dev/null
        printf "[ ${green}OK${normal} ]\n"

        printf "|-\-\-\-\-> Done! %-39s"
        printf "[ ${green}OK${normal} ]\n"

        if [ "$(pgrep -f "lein")" ]
        then
            echo -e "$LOGO Infused and Ready\n"
        else
            echo -e "[${red}Something went wrong${normal} :("
        fi
    else
        echo -e "$LOGO - Already Running\n"
    fi
}

function GreenteaKiller {
    if [ "$(pgrep -f lein)" ]
    then
        printf "|-\-\-\-\-> Killing Greentea %-45s"
        sudo pkill -f "lein"
        if [ "$(pgrep -f lein)" ]
        then
            printf "[ ${green}OK${normal} ]\n"
        else
            printf "[ ${red}FAILED${normal} ]\n"
        fi
    else
        echo -e "$STR" `echo -e "[ ${red}$LOGO NOT Running${normal} ]"`
    fi
}

function GreenteaStatus {
    TABS="\t\t\t\t\t"
    STR="$LOGO\n\n$TABS"
    CODE="`curl -sL -w "%{http_code}" "$URL" -o /dev/null`"
    STR2="\n$TABS Code: $CODE\n"
    if [ "$(pgrep -f lein)" ]
    then
        echo -e "$STR" `echo -e "[ ${green}Running${normal} ] "` "$STR2"
    else
        echo -e "$STR" `echo -e "[ ${red}NOT Running${normal} ]"` "$STR2"
    fi
}

function Commands {
    printf "Available Commands:\n"
    echo -e "$AVAILABLE_COMMANDS"
}

function Usage {
    echo "Usage: teabag <command>"
    Commands
    Processes
}

function Processes {
    printf "Available Processes:\n"
    echo -e "$AVAILABLE_PROCESSES"
}

function ServiceApache {
    sudo service apache2 restart
}

function Help {
    if [ $NUM_ARGS -lt 2 ]
    then
        echo "Help usage: teabag help <command>"
    else
        if [ ${ARGS[1]} == "status" ]
        then
            echo "usage: teabag status"
            printf "\t> Returns the status of the currently running processes.\n"
        elif [ ${ARGS[1]} == "help" ]
        then
            echo "usage: teabag help <command>"
            printf "\t> Provides a terse description about passable commands.\n"
        elif [ ${ARGS[1]} == "kill"  || ${ARGS[1]} == "stop" ]
        then
            echo "usage: teabag kill"
            printf "\t> Kills all currently running processes.\n"
            echo "usage: teabag kill <process>"
            printf "\t> Kills the specified running processes.\n"
        elif [ ${ARGS[1]} == "infuse" || ${ARGS[1]} == "start" ]
        then
            echo "usage: teabag"
            echo "usage: teabag infuse"
            printf "\t> Starts all configured processes.\n"
            echo "usage: teabag infuse <process>"
            printf "\t> Starts the specified teabag process.\n"
        elif [ ${ARGS[1]} == "apache" ]
        then
            echo "usage: teabag apache"
            printf "\t> Restarts the apache server.\n"
        elif [ ${ARGS[1]} == "processes" ]
        then
            echo "usage: teabag processes"
            printf "\t> Lists all configured processes.\n"
        elif [ ${ARGS[1]} == "usage" ]
        then
            echo "usage: teabag commands"
            printf "\t> Lists all usable commands.\n"
        else
            echo "${ARGS[1]}" "is not a valid command!"
            echo -e "Did you Mean:\n" "$AVAILABLE_COMMANDS"
        fi
    fi
}

##################################
#        Global Variables        #
##################################

NUM_ARGS=("$#")
ARGS=("$@")
# TODO: Turn into arrays and parse them out within their appropriate functions
AVAILABLE_COMMANDS="\tstatus\n \tapache\n \tkill\n \tusage\n \tinfuse\n \tprocesses\n \thelp\n start\n \tstop\n"
AVAILABLE_PROCESSES="\tgreentea"

##################################
#          Main Method           #
##################################

if [ $# != 0 ]
then
    if [ "$1" == "status" ]
    then
        GreenteaStatus
    elif [ "$1" == "kill" ] || [ "$1" == "stop" ]
    then
        GreenteaKiller
    elif [ "$1" == "infuse" ] || [ "$1" == "start" ]
    then
        GreenteaRunner
    elif [ "$1" == "help" ] || [ "$1" == "-h" ]
    then
        Help
    elif [ "$1" == "processes" ]
    then
        Processes
    elif [ "$1" == "commands" ]
    then
        Commands
    elif [ "$1" == "apache" ]
    then
        ServiceApache
    else
        Usage
    fi
else
    GreenteaRunner
fi
